### ISSUE TITLE
Update social media stuff

### ISSUE THREAD

**Issue by 3ygun** [esportsinitiative/esportsinitiative.github.io#10]
Use an object to better manage the footer page allowing for looping across all social media
- [x] Update all the Social Media to objects
  - [x] username
  - [x] icon
  - [x] link
- [x] Change the footer to use this new model
- [x] Should look like the old footer

**Comment by 3ygun** [comment]
Old:

``` ruby
{% if site.twitch_username %}
<li>
  {% include icon-all.html icon="fa fa-twitch" link=site.twitch_link username=site.twitch_username %}
</li>
{% endif %}

{% if site.twitter_username %}
<li>
  {% include icon-all.html icon="fa fa-twitter" link=site.twitter_link username=site.twitter_username %}
</li>
{% endif %}

{% if site.facebook_username %}
<li>
  {% include icon-all.html icon="fa fa-facebook-official" link=site.facebook_link username=site.facebook_username %}
</li>
{% endif %}

{% if site.instagram_username %}
<li>
  {% include icon-all.html icon="fa fa-instagram" link=site.instagram_link username=site.instagram_username %}
</li>
{% endif %}

{% if site.challonge_username %}
<li>
  {% include icon-all.html icon="fa fa-trophy" link=site.challonge_link username=site.challonge_username %}
</li>
{% endif %}

{% if site.youtube_username %}
<li>
  {% include icon-all.html icon="fa fa-youtube" link=site.youtube_link username=site.youtube_username %}
</li>
{% endif %}

{% if site.github_username %}
<li>
  {% include icon-all.html icon="fa fa-github" link=site.github_link username=site.github_username %}
</li>
{% endif %}

{% if site.email %}
<li>
  {% assign email_link = "mailto:" | append: site.email %}
  {% include icon-all.html icon="fa fa-envelope" link=site.email_link username=site.email %}
</li>
{% endif %}
```

``` yaml
# Social Media
twitter_username:   ESI_OSU
facebook_username:  esportsinitiative
instagram_username: esportsinitiative
twitch_username:    esportsinitiative
challonge_username: esportsinitiative
youtube_username:   esportsinitiative # Though actually: ESportsInitiative
github_username:    esportsinitiative

# Social Media Links
twitter_link:       http://twitter.com/ESI_OSU
facebook_link:      http://facebook.com/esportsinitiative
instagram_link:     http://instagram.com/esportsinitiative
twitch_link:        http://twitch.com/esportsinitiative
challonge_link:     http://challonge.com/users/esportsinitiative
youtube_link:       http://youtube.com/user/ESportsInitiative
github_link:        http://github.com/esportsinitiative
```

**Comment by 3ygun** [comment]
Closed by #18 with newest:

``` yml
# Social Media
# Icons: http://fontawesome.io/icons/

- service:      "twitch"
  name:         "esportsinitiative"
  link:         "https://twitch.com/esportsinitiative"
  icon:         "fa fa-twitch"

- service:      "twitter"
  name:         "ESI_OSU"
  link:         "https://twitter.com/ESI_OSU"
  icon:         "fa fa-twitter"

# ETC....
```
